### ISSUE TITLE
As PO I want the testreports to have an additional field with a link to the related standard

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#204]
such that users can browse to the website of the standard to which the testset belongs 

**Toelichting**:
This issue applies to both consumer as provider reports

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
This is thus for both consumer and provider, and both about the detail-view of the session and related to creating a new session.

For the detail-view of the session there should be a link to an overview-page showing the relevant information about the session type. 
This relevant information should be filled out in the admin module.

For the 'start session' form, instead of a dropdown of possible session types there should be radiobuttons, with a link to the (above) overview page about the session type.

The session type should have a simple WYSIWYG-field allowing content marked up properly. This should at least also allow linking out to the relevant websites which contain further details.

**Comment by alextreme** [comment]
This has been implemented in staging and discussed with Henri.

Each Consumer session-type and Provider test-scenario now has a description field in the admin:

![Screenshot_2019-06-27_18-03-27](https://user-images.githubusercontent.com/226839/60281854-025ccb00-9906-11e9-88c7-d3fff5b3ebe1.png)

The details of each session-type / test-scenario can be found via the info-link's:

https://vng-staging.maykin.nl/create

![Screenshot_2019-06-27_18-00-27](https://user-images.githubusercontent.com/226839/60282826-228d8980-9908-11e9-9265-b49639be4ac0.png)

**Comment by alextreme** [comment]
@AlviseSembenico re-reading the US, Henri wants these links to come back (primarily) in the detail/report views:

https://vng-staging.maykin.nl/server/dfbe8afc-05b6-49b2-bf1a-26d62eefa2b9

I suggest to add the [info] link also to the name of the session-type / test-scenario on this view (eg. behind 'ZGW api tests'). Feel free to make this a button if you think it's nicer.

![Screenshot_2019-06-27_18-21-13](https://user-images.githubusercontent.com/226839/60282971-6e403300-9908-11e9-8907-8006403c0a9b.png)

**Comment by alextreme** [comment]
@AlviseSembenico  Looking good for how this is done for provider testruns:

![Screenshot_2019-07-10_14-49-35](https://user-images.githubusercontent.com/226839/60970385-249d1280-a322-11e9-90ac-40256238b858.png)

On the consumer side the description is shown on the detail page. Please ensure we link out to the description instead with a button, as with the provider.
