### ISSUE TITLE
Validatie op het eindresultaat US #36

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#44]
Op basis van US #36 is ook validatie mogelijk op het eindresultaat.

Wat hiervoor nodig is, is de mogelijkheid van de testvoorziening om na het afronden van een test-run van de client tegen de referentiecomponenten een reeks validatie GET-calls uitvoeren.

Hiermee kan bijvoorbeeld gecontroleerd worden of de MOR zaak daadwerkelijk is aangemaakt conform de verwachtingen.

**Comment by alextreme** [comment]
Restpunt uit sprint 1. Aan @HenriKorver om opname in vervolgsprint te bepalen

**Comment by JanWillemKooi** [comment]
@alextreme Alex, kan je aub reviewen.

**Comment by alextreme** [comment]
Verified to be working as expected on staging. I've added a Postman collection to the Demo API session type which performs a GET to /api/v2/quotes after stopping the session:

![Screenshot_2019-04-12_18-46-00](https://user-images.githubusercontent.com/226839/56054183-65eb4980-5d56-11e9-9fe0-71bc56893719.png)

The fact that the Postman collection was run is currently only shown with a checkmark (this was the initial and only output after it was originally implemented).

I've asked Alvise (with low priority) to show more details on the performed Postman collection run, with if possible reuse of the Test Provider way of showing the newman details.

**Comment by alextreme** [comment]
This has been implemented and is ready for review

**Comment by HenriKorver** [comment]
Check op eindresultaat faalt maar zou moeten slagen (immers er zijn quotes in de database)

![afbeelding](https://user-images.githubusercontent.com/37145898/57295007-b04bb600-70c9-11e9-9206-c945b2495176.png)

@alextreme Hebben jullie dit al echt goed getest?

**Comment by alextreme** [comment]
Op de test-omgeving volledig en op staging op basis van de eerdere test-sessie, ik loop er vanmiddag nogmaals doorheen.

**Comment by alextreme** [comment]
@AlviseSembenico for you to tackle. I updated the Postman collection for the Test Consumer Demo API session type on vng-staging to deal with the requested subdomain/path split however this doesn't work as expected (the assertion still fails). Perhaps the old collection is still used/cached somewhere?

**Comment by AlviseSembenico** [comment]
@alextreme I see that there is no injection of the url in the postman. Is the key to be replaced {{demo-api}}?

**Comment by alextreme** [comment]
The postman collection for the Demo API session type has been updated by Alvise, this is now working as expected:

![Screenshot_2019-05-17_11-17-41](https://user-images.githubusercontent.com/226839/57917675-7b8fe980-7895-11e9-8aad-585f71317112.png)

**Comment by HenriKorver** [comment]
I did not succeed to get it working for the docker version of demo-api:

https://vng-staging.maykin.nl/860/

@alextreme or @AlviseSembenico: Is this a bug or do I do something wrong?

![afbeelding](https://user-images.githubusercontent.com/37145898/57933650-21574e80-78be-11e9-82e8-291cb4dda267.png)

**Comment by alextreme** [comment]
We are using the regular Demo API session for this, only this session type's postman collection has been updated. So review using the non-Docker session.

Each Postman collection which is uploaded needs to make use of the endpoints as variables. In this case {{ quotes }} is used, however the variable which should be used is {{ demo-api }}. This was corrected for the regular Demo API session type.

**Comment by HenriKorver** [comment]
Allright I will only review the non-docker version. But could you make a user story for fixing this problem in the docker-version?

**Comment by alextreme** [comment]
I've removed the incorrect PM collection for the MOR docker-sessiontype

**Comment by HenriKorver** [comment]
I am confused because the PM collection you removed is correct in my opinion. It does include the {{demo-api}} variable for detemining the path the docker API. It also includes {{quote}} which is created during the execution of the collection.

**Comment by alextreme** [comment]
It seems I mentioned the wrong variable. As you can see the first call is 'GET None/quotes' which naturally is an invalid URL. If that would have been resolved the {{ quotes }} would indeed have been filled in with the URL to the quote found.

Feel free to try this out with more complicated PM collections, however use the regular Demo API one as a starting point as this does make correct use of the endpoint-variable.

**Comment by HenriKorver** [comment]
I have tested the non-docker version and it works. Although there is a small problem with the demo-api variable. In the user interface

![afbeelding](https://user-images.githubusercontent.com/37145898/57950997-2da4d100-78e9-11e9-8fb7-4c1cc18928f5.png)


 it referes to  for instance https://155811995866-vng-staging.maykin.nl/demo-api/api/v2. But in the binding to the postman collection it referes to https://155811995866-vng-staging.maykin.nl. Since I know this inconsitency I can work around it but it is very confusing and should be solved.

I did not succeed in testing the docker-version. There the variable demo-api refers in the user interface to (for instance) https://155811934185-vng-staging.maykin.nl/api/v2/ but in the binding to the postman collection it is empty (None)

![afbeelding](https://user-images.githubusercontent.com/37145898/57950960-0fd76c00-78e9-11e9-8a25-63577597bd13.png)

**Comment by HenriKorver** [comment]
To summerize the problem: in the non-docker version the variable `demo-api` refers to the base-url (host-name) of the path in the binding to the Postman collection.

![afbeelding](https://user-images.githubusercontent.com/37145898/57969943-380fab00-797b-11e9-9e5c-ea61b42acbc8.png)

But is should refer to the concatenation of the Url- and the path-field. So "https://ref.tst.vng.cloud" + 
"/demo-api/api/v2" = "https://ref.tst.vng.cloud/demo-api/api/v2". In the latter case it refers to the same url as in the user interface:

![afbeelding](https://user-images.githubusercontent.com/37145898/57970054-e1a36c00-797c-11e9-8fee-1d0aa61a1341.png)


In the docker-version of the demo-api test this problem gets really serious because the `demo-api` variable refers to an empty Url-field:

![afbeelding](https://user-images.githubusercontent.com/37145898/57970019-532eea80-797c-11e9-847b-e01494d94ad4.png)

**Comment by alextreme** [comment]
I've spit off the Docker+PM collection bug into #183, you are correct.

Wouldn't it be more consistent to not add the path to the end of the URL-variable and specify the path in your postman collection? As far as I understand the path would only come back in the user interface to provide a starting-point for the user to browse.

**Comment by alextreme** [comment]
Henri, I've added your latest Postman collection to the Demo API session-type. This now works as expected in my eyes:

https://vng-staging.maykin.nl/2996e793-faae-4f95-aa4f-2a8929fe8126/

![Screenshot_2019-06-27_17-51-11](https://user-images.githubusercontent.com/226839/60280967-45b63a00-9904-11e9-9e6a-737da14dc8d4.png)

**Comment by alextreme** [comment]
I've also verified that the Demo API (Docker) session-type is working as expected:

https://vng-staging.maykin.nl/2996e793-faae-4f95-aa4f-2a8929fe8126/

![Screenshot_2019-06-27_17-54-34](https://user-images.githubusercontent.com/226839/60281178-bbbaa100-9904-11e9-9824-2c29a3779d67.png)

![Screenshot_2019-06-27_17-54-45](https://user-images.githubusercontent.com/226839/60281182-bf4e2800-9904-11e9-86f8-2b1a97bc4392.png)

**Comment by HenriKorver** [comment]
@alextreme I get a lot of errors: https://vng-staging.maykin.nl/16d493d5-5677-4ca4-af3b-b889cf32729d/

**Comment by alextreme** [comment]
@HenriKorver I've retested and it is working for me:

https://vng-staging.maykin.nl/99d20498-10ec-4e14-9cc6-b34f89b61ae2/

![Screenshot_2019-07-04_17-57-45](https://user-images.githubusercontent.com/226839/60678591-48290e80-9e85-11e9-8996-9cab0858ca91.png)

Lets check this together next Thursday
